My Project: io.c File Reference
io.c File Reference
#include "io.h"
Functions
void viderBuffer ()
void afficher (char grille[10][12])
void menu (char grille[10][12])
Function Documentation
afficher()
void afficher (char grille[10][12])
Definition at line 10 of file io.c.
Referenced by jeu().
{
     int lig,col;
     printf("-------------------------------------\n");
     printf("0  1  2  3  4  5  6  7  8  9  10 11 |\n");
     printf("-------------------------------------\n");
     for(lig=0;lig<10;lig++) {
         for(col=0;col<12;col++)
             printf("%c  ",grille[lig][col]);
         printf("\n");
     }
 }
menu()
void menu (char grille[10][12])
Definition at line 22 of file io.c.
References jeu(), and viderBuffer().
Referenced by main().
{
     int choix;
     printf("\n----------------------------------PUISSANCE 6--------------------------------\n");
     printf("\n*                              Menu du jeu :                                 *\n");
     printf("\n*                          1) Joueur vs Joueur                               *\n");
     printf("\n*                          0) Quitter                                        *\n");
     printf("\n------------------------------------------------------------------------------\n");
     do { //tant qu'on a pas 1 ou 0
         choix = -1;
         printf("\n Entrez le mode : ");
         scanf("%d", &choix);
         viderBuffer();
         if(choix != 0 && choix != 1)
             printf("Choisissez 1 ou 0 !\n\n");
     }while(choix != 1 && choix != 0);
     choix == 1 ? jeu(grille) : exit(0);
 }
viderBuffer()
void viderBuffer ()
Definition at line 3 of file io.c.
Referenced by jeu(), and menu().
                    {
   int c = 0;
   while(c != '\n' && c != EOF){
     c = getchar();
   }
 }